### PR TITLE
feat: Use SWC for fast test execution

### PR DESCRIPTION
**Pull request by andersfischernielsen**
This PR will use [SWC](https://swc.rs/docs/usage/jest) for `jest` execution in order to speed up test runs and fail faster to catch errors earlier.

### CODE REVIEW

**Comment by pekala** [comment]
Hm... Do you think the additional complexity of running SWC is worth here for saving 4 seconds? I'm not convinced

**Comment by pekala** [comment]
Tried running it 3 times, and each time the whole job with SWC took longer than the baseline :D

**Comment by andersfischernielsen** [comment]
> Hm... Do you think the additional complexity of running SWC is worth here for saving 4 seconds? I'm not convinced

I don't understand you point about additional complexity here 🤔 Either we depend on `ts-jest` as we do currently or we depend on `@swc/jest`. Whether it's one dependency or the other doesn't matter - the only difference is that we gain additional performance with a Rust tool rather than a slower Node tool

**Comment by pekala** [comment]
The surface for issues is bigger with `@swc/jest` (e.g. just look at yarn.lock) - that's the price to pay for the speed. For bigger test suites it could be a great trade-off, here I'm not convinced.
But I don't really mind much either - let's merge it!

**Pull request merged**
